export const BRAND_PRIMARY_DARK = '#FF6A3D'
export const BRAND_PRIMARY_LIGHT = '#E04E28'
export const BRAND_PASSIVE_DARK = '#4A8EC7'
export const BRAND_PASSIVE_LIGHT = '#2563EB'

export const BRAND_BG_DARK = '#0B0F14'
export const BRAND_BG_LIGHT = '#F7F7F8'
export const BRAND_SURFACE_DARK = '#0F1620'
export const BRAND_SURFACE_LIGHT = '#FFFFFF'
export const BRAND_MUTED_DARK = '#141C26'
export const BRAND_MUTED_LIGHT = '#EEF0F3'
export const BRAND_BORDER_DARK = '#233041'
export const BRAND_BORDER_LIGHT = '#D8DEE6'
export const BRAND_TEXT_DARK = '#E8EDF3'
export const BRAND_TEXT_LIGHT = '#0B0F14'
export const BRAND_TEXT_MUTED_DARK = '#A7B0BC'
export const BRAND_TEXT_MUTED_LIGHT = '#4B5563'
export const BRAND_CONTAINER_LIGHT = '#111827'

export const LEGACY_DEFAULT_COLOR_PRIMARY = '#00b96b'
