import { createHash } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'

import { getDataPath } from '@main/utils'
import { findSkillMdPath } from '@main/utils/markdownParser'
import type { AgentRuntimeKind, InstalledSkill } from '@types'

export interface RuntimeSkillFileSyncInput {
  runtimeKind: AgentRuntimeKind
  cwd: string
  agentId?: string
  sessionId?: string
  skills: InstalledSkill[]
}

export interface RuntimeSkillFileSyncResult {
  skillId: string
  runtimeKind: AgentRuntimeKind
  externalRef: string
  checksum: string
  status: 'synced' | 'error'
  lastError?: string
}

export async function materializeRuntimeSkillFiles(
  input: RuntimeSkillFileSyncInput
): Promise<RuntimeSkillFileSyncResult[]> {
  const enabledSkills = input.skills.filter((skill) => skill.isEnabled)
  const results = await Promise.all(enabledSkills.map((skill) => materializeRuntimeSkill(input, skill)))

  if (input.runtimeKind === 'opencode') {
    await writeOpenCodeAgentManifest(input, results)
  }

  if (input.runtimeKind === 'uar') {
    await writeUarSkillManifest(input, results)
  }

  return results
}

async function materializeRuntimeSkill(
  input: RuntimeSkillFileSyncInput,
  skill: InstalledSkill
): Promise<RuntimeSkillFileSyncResult> {
  const externalRef = runtimeSkillPath(input.runtimeKind, input.cwd, skill.folderName)

  try {
    const sourceDir = path.join(getDataPath('Skills'), skill.folderName)
    const sourceSkillPath = await findSkillMdPath(sourceDir)
    if (!sourceSkillPath) {
      throw new Error(`Missing SKILL.md for ${skill.folderName}`)
    }

    const sourceContent = await fs.readFile(sourceSkillPath, 'utf8')
    const generatedContent = [
      '<!-- Generated by The Boss runtime skill bridge. Canonical source remains the app skill registry. -->',
      `<!-- skill_id=${skill.id} folder=${skill.folderName} checksum=${skill.contentHash} -->`,
      sourceContent
    ].join('\n')

    await fs.mkdir(path.dirname(externalRef), { recursive: true })
    await fs.writeFile(externalRef, generatedContent)

    return {
      skillId: skill.id,
      runtimeKind: input.runtimeKind,
      externalRef,
      checksum: checksum(generatedContent),
      status: 'synced'
    }
  } catch (error) {
    return {
      skillId: skill.id,
      runtimeKind: input.runtimeKind,
      externalRef,
      checksum: skill.contentHash,
      status: 'error',
      lastError: error instanceof Error ? error.message : String(error)
    }
  }
}

function runtimeSkillPath(runtimeKind: AgentRuntimeKind, cwd: string, folderName: string): string {
  switch (runtimeKind) {
    case 'claude':
      return path.join(cwd, '.claude', 'skills', folderName, 'SKILL.md')
    case 'codex':
      return path.join(cwd, '.codex', 'skills', folderName, 'SKILL.md')
    case 'opencode':
      return path.join(cwd, '.opencode', 'skills', folderName, 'SKILL.md')
    case 'uar':
      return path.join(cwd, '.uar', 'skills', folderName, 'SKILL.md')
  }
}

async function writeOpenCodeAgentManifest(
  input: RuntimeSkillFileSyncInput,
  results: RuntimeSkillFileSyncResult[]
): Promise<void> {
  const agentId = input.agentId ?? 'agent'
  const manifestPath = path.join(input.cwd, '.opencode', 'agents', `${agentId}.json`)
  await fs.mkdir(path.dirname(manifestPath), { recursive: true })
  await fs.writeFile(
    manifestPath,
    `${JSON.stringify(
      {
        agentId: input.agentId,
        sessionId: input.sessionId,
        skills: results.filter((result) => result.status === 'synced').map((result) => result.externalRef)
      },
      null,
      2
    )}\n`
  )
}

async function writeUarSkillManifest(
  input: RuntimeSkillFileSyncInput,
  results: RuntimeSkillFileSyncResult[]
): Promise<void> {
  const manifestPath = path.join(input.cwd, '.uar', 'skills.json')
  await fs.mkdir(path.dirname(manifestPath), { recursive: true })
  await fs.writeFile(
    manifestPath,
    `${JSON.stringify(
      {
        agentId: input.agentId,
        sessionId: input.sessionId,
        skills: results
          .filter((result) => result.status === 'synced')
          .map((result) => ({
            skillId: result.skillId,
            path: result.externalRef,
            checksum: result.checksum
          }))
      },
      null,
      2
    )}\n`
  )
}

function checksum(content: string): string {
  return createHash('sha256').update(content).digest('hex')
}
