import { createHash } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'

import { loggerService } from '@logger'
import { getDataPath } from '@main/utils'
import { findSkillMdPath } from '@main/utils/markdownParser'
import type { AgentRuntimeKind, InstalledSkill } from '@types'

import { BaseService } from '../../BaseService'
import { agentRuntimeSkillSyncsTable } from '../../database/schema'

const logger = loggerService.withContext('RuntimeSkillBridgeService')

export interface RuntimeSkillSyncInput {
  runtimeKind: AgentRuntimeKind
  cwd: string
  agentId?: string
  sessionId?: string
  skills: InstalledSkill[]
}

export interface RuntimeSkillSyncResult {
  skillId: string
  runtimeKind: AgentRuntimeKind
  externalRef: string
  checksum: string
  status: 'synced' | 'error'
  lastError?: string
}

export class RuntimeSkillBridgeService extends BaseService {
  private static instance: RuntimeSkillBridgeService | null = null

  static getInstance(): RuntimeSkillBridgeService {
    if (!RuntimeSkillBridgeService.instance) {
      RuntimeSkillBridgeService.instance = new RuntimeSkillBridgeService()
    }
    return RuntimeSkillBridgeService.instance
  }

  async syncRuntimeSkills(input: RuntimeSkillSyncInput): Promise<RuntimeSkillSyncResult[]> {
    const results = await materializeRuntimeSkillFiles(input)
    await Promise.all(results.map((result) => this.recordSync(input, result)))
    return results
  }

  private async recordSync(input: RuntimeSkillSyncInput, result: RuntimeSkillSyncResult): Promise<void> {
    try {
      const db = await this.getDatabase()
      const now = Date.now()
      const id = [input.runtimeKind, input.agentId ?? 'no-agent', input.sessionId ?? 'no-session', result.skillId].join(
        ':'
      )

      await db
        .insert(agentRuntimeSkillSyncsTable)
        .values({
          id,
          agent_id: input.agentId,
          session_id: input.sessionId,
          skill_id: result.skillId,
          runtime_kind: input.runtimeKind,
          external_ref: result.externalRef,
          checksum: result.checksum,
          status: result.status,
          last_error: result.lastError,
          synced_at: result.status === 'synced' ? now : null,
          created_at: now,
          updated_at: now
        })
        .onConflictDoUpdate({
          target: agentRuntimeSkillSyncsTable.id,
          set: {
            external_ref: result.externalRef,
            checksum: result.checksum,
            status: result.status,
            last_error: result.lastError,
            synced_at: result.status === 'synced' ? now : null,
            updated_at: now
          }
        })
    } catch (error) {
      logger.warn('Failed to record runtime skill sync status', {
        runtimeKind: input.runtimeKind,
        skillId: result.skillId,
        error: error instanceof Error ? error.message : String(error)
      })
    }
  }
}

export async function materializeRuntimeSkillFiles(input: RuntimeSkillSyncInput): Promise<RuntimeSkillSyncResult[]> {
  const enabledSkills = input.skills.filter((skill) => skill.isEnabled)
  const results = await Promise.all(enabledSkills.map((skill) => materializeRuntimeSkill(input, skill)))

  if (input.runtimeKind === 'opencode') {
    await writeOpenCodeAgentManifest(input, results)
  }

  if (input.runtimeKind === 'uar') {
    await writeUarSkillManifest(input, results)
  }

  return results
}

async function materializeRuntimeSkill(
  input: RuntimeSkillSyncInput,
  skill: InstalledSkill
): Promise<RuntimeSkillSyncResult> {
  const externalRef = runtimeSkillPath(input.runtimeKind, input.cwd, skill.folderName)

  try {
    const sourceDir = path.join(getDataPath('Skills'), skill.folderName)
    const sourceSkillPath = await findSkillMdPath(sourceDir)
    if (!sourceSkillPath) {
      throw new Error(`Missing SKILL.md for ${skill.folderName}`)
    }

    const sourceContent = await fs.readFile(sourceSkillPath, 'utf8')
    const generatedContent = [
      '<!-- Generated by The Boss runtime skill bridge. Canonical source remains the app skill registry. -->',
      `<!-- skill_id=${skill.id} folder=${skill.folderName} checksum=${skill.contentHash} -->`,
      sourceContent
    ].join('\n')

    await fs.mkdir(path.dirname(externalRef), { recursive: true })
    await fs.writeFile(externalRef, generatedContent)

    return {
      skillId: skill.id,
      runtimeKind: input.runtimeKind,
      externalRef,
      checksum: checksum(generatedContent),
      status: 'synced'
    }
  } catch (error) {
    return {
      skillId: skill.id,
      runtimeKind: input.runtimeKind,
      externalRef,
      checksum: skill.contentHash,
      status: 'error',
      lastError: error instanceof Error ? error.message : String(error)
    }
  }
}

function runtimeSkillPath(runtimeKind: AgentRuntimeKind, cwd: string, folderName: string): string {
  switch (runtimeKind) {
    case 'claude':
      return path.join(cwd, '.claude', 'skills', folderName, 'SKILL.md')
    case 'codex':
      return path.join(cwd, '.codex', 'skills', folderName, 'SKILL.md')
    case 'opencode':
      return path.join(cwd, '.opencode', 'skills', folderName, 'SKILL.md')
    case 'uar':
      return path.join(cwd, '.uar', 'skills', folderName, 'SKILL.md')
  }
}

async function writeOpenCodeAgentManifest(
  input: RuntimeSkillSyncInput,
  results: RuntimeSkillSyncResult[]
): Promise<void> {
  const agentId = input.agentId ?? 'agent'
  const manifestPath = path.join(input.cwd, '.opencode', 'agents', `${agentId}.json`)
  await fs.mkdir(path.dirname(manifestPath), { recursive: true })
  await fs.writeFile(
    manifestPath,
    `${JSON.stringify(
      {
        agentId: input.agentId,
        sessionId: input.sessionId,
        skills: results.filter((result) => result.status === 'synced').map((result) => result.externalRef)
      },
      null,
      2
    )}\n`
  )
}

async function writeUarSkillManifest(input: RuntimeSkillSyncInput, results: RuntimeSkillSyncResult[]): Promise<void> {
  const manifestPath = path.join(input.cwd, '.uar', 'skills.json')
  await fs.mkdir(path.dirname(manifestPath), { recursive: true })
  await fs.writeFile(
    manifestPath,
    `${JSON.stringify(
      {
        agentId: input.agentId,
        sessionId: input.sessionId,
        skills: results
          .filter((result) => result.status === 'synced')
          .map((result) => ({
            skillId: result.skillId,
            path: result.externalRef,
            checksum: result.checksum
          }))
      },
      null,
      2
    )}\n`
  )
}

function checksum(content: string): string {
  return createHash('sha256').update(content).digest('hex')
}

export const runtimeSkillBridgeService = RuntimeSkillBridgeService.getInstance()
